### ISSUE TITLE
Hal for nash oreo

### ISSUE THREAD

**Issue by invisiblek** [MotorolaMobilityLLC/motorola-external-v4l2_hal#2]
vermagic=4.4.78-perf-g6174029 SMP preempt mod_unload modversions aarch64

This is GPL V2 according to strings on the module. Where's the source?

**Comment by Uzephi** [comment]
Yes, can we please get the hal source for the Nash?

http://www.gnu.org/licenses/gpl-violation.html

@charleseb 

Edit: because of this being a two partition device, and a different chipset, I am sure the current branch available for Hal will not work for our device. It makes me wonder how many other devices that have a GPL V2 HAL haven't had their sources properly disclosed...

**Comment by charleseb** [comment]
Hi all,

I've missed this git. I'm working to release it by Tuesday.

Thanks,
Charles

**Comment by charleseb** [comment]
Hi all,

Versions released.
https://github.com/MotorolaMobilityLLC/motorola-external-v4l2_hal/releases

----
Thanks,
Charles

**Comment by invisiblek** [comment]
<3
